name: Playwright E2E Tests Manual

on:
  workflow_dispatch:
    inputs:
      testFile:
        description: 'Test file'
        required: false
        default: '(todos)'
        type: choice
        options:
          - (todos)
          - tests/flujoA_steps.spec.ts
          - tests/flujoB_steps.spec.ts

      reporter:
        description: 'Reporter type'
        required: true
        default: 'html'
        type: choice
        options:
          - html
          - allure
          - both

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install deps
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test ${{ inputs.testFile }} --reporter=line || true